// Shared constants for game entities/components.
export const PLAYER_SPEED = 24
export const PLAYER_SPEED_CAP = 50
export const SPEED_DEBUFF_FACTOR = 0.6
export const SPEED_DEBUFF_DURATION_MS = 4000
export const BOUNDARY_LIMIT = 50
export const SHAPE_PATH_RADIUS = 24
export const ENEMY_SPEED = 18
export const RUNNER_SPEED_MULTIPLIER = 1.6
export const BOSS_SPEED = 6
export const TRIANGLE_BOSS_SPEED_MULT = 2.3
export const WAVE_INTERVAL = 2000
export const BULLET_SPEED = 38
export const BULLET_LIFETIME = 3000
export const FIRE_RATE = 200
export const BULLET_POOL_SIZE = 50
export const PICKUP_COLLECT_DISTANCE = 3.8
export const AIM_RAY_LENGTH = 8
export const MAX_PICKUPS = 25
export const BOMB_DAMAGE = 4
export const BOMB_STUN_MS = 1400
export const BOMB_CONTACT_RADIUS = 1.4
export const BOMB_AOE_RADIUS = 6.2
export const BOMB_UP_VEL = 12
export const BOMB_GRAVITY = 24
export const BOMB_SPAWN_INTERVAL_MS = 250
export const BOMB_ABILITY_DURATION_MS = 6000
export const SPEED_BUFF_DURATION_MS = 4000
export const SPEED_BOOST_LIFETIME = 4500
export const SPEED_BOOST_RADIUS_MIN = 10
export const SPEED_BOOST_RADIUS_MAX = 18
export const SPEED_TUNING_BASE = 14
export const SPEED_SCALE = Math.max(0.5, PLAYER_SPEED / SPEED_TUNING_BASE)
export const MINION_MAX_SPEED = 12
export const TRIANGLE_CHARGE_MAX = 18
export const TRIANGLE_CIRCLE_MAX = 12
export const DAMAGE_SCALE_PER_WAVE = 0.04
export const DAMAGE_SCALE_MAX = 4.0
export const ENEMY_SPEED_SCALE_PER_WAVE = 0.03
export const ENEMY_SPEED_SCALE_MAX = 1.5
export const APPROACH_SLOW_RADIUS = 2.5
export const POST_LAND_SETTLE = 0.3
export const KNOCKBACK = { minion: 12.0, boss: 8.0, triangle: 7.0 }
export const KNOCKBACK_DECAY = { minion: 8.0, boss: 6.0, triangle: 6.0 }
export const KNOCKBACK_DISTANCE_MAX = 8.0
export const PORTAL_LIFETIME = 4500
export const PORTALS_PER_WAVE_MIN = 2
export const PORTALS_PER_WAVE_MAX = 4
export const PORTAL_RADIUS_MIN = 12
export const PORTAL_RADIUS_MAX = 20
export const PORTAL_STAGGER_MS = 260
export const DROP_SPAWN_HEIGHT = 8
export const DROP_SPEED = 10
export const CONTACT_DAMAGE = { minion: 2, boss: 20, triangle: 31, cone: 42 }
